#' @title Template titel
#' <%=ifelse(exists("A"), "@param A Symmetrix matrix whose maximum eigenvalue is to be computed.", "") %>
#' <%=ifelse(exists("aggregation"), "@param aggregation A character vector of length \\code{n_vars} with elements being \\code{'identity'}, \\code{'average'} or \\code{'triangular'} to indicate the type of aggregation scheme to assume.", "") %>
#' <%=ifelse(exists("chisq_val"), "@param chisq_val The value in the corresponding chi-square distribution; if the normal quadratic form exceeds this, the pdf is 0.", "") %>
#' <%=ifelse(exists("check_roots"), "@param check_roots Logical, if roots of the companion matrix are to be checked to ensure stationarity.", "") %>
#' <%=ifelse(exists("d"), "@param d The matrix of size \\code{(n_T + n_lags) * n_determ} of deterministic terms.", "") %>
#' <%=ifelse(exists("D_mat"), "@param D_mat The \\code{D} matrix (from \\code{\\link{build_DD}}).", "") %>
#' <%=ifelse(exists("d_fcst"), "@param d_fcst The deterministic terms for the forecasting period.", "") %>
#' <%=ifelse(exists("freq"), "@param freq Character vector with elements 'm' (monthly) or 'q' (quarterly) for sampling frequency.", "") %>
#' <%=ifelse(exists("h0"), "@param h0 The initial state (\\code{(n_vars*n_lags)*1}).", "") %>
#' <%=ifelse(exists("Lambda"), "@param Lambda The Lambda matrix (size \\code{n_vars* (n_vars*n_lags)}).", "") %>
#' <%=ifelse(exists("lambda1"), "@param lambda1 The overall tightness.", "") %>
#' <%=ifelse(exists("lambda1_grid"), "@param lambda1_grid The grid of values to use for lambda1.", "") %>
#' <%=ifelse(exists("lambda2_grid"), "@param lambda2_grid The grid of values to use for lambda2.", "") %>
#' <%=ifelse(exists("lambda2"), "@param lambda2 The lag decay.", "") %>
#' <%=ifelse(exists("lambda3"), "@param lambda3 The tightness of the intercept prior variance.", "") %>
#' <%=ifelse(exists("lH"), "@param lH A list of length \\code{n_T}, where \\code{M_Lambda[[t]]} corresponds to \\eqn{M_t\\Lambda}. The column dimension of each element should be \\code{n_lags*n_vars}, but the row dimension may vary.", "") %>
#' <%=ifelse(exists("init_Pi"), "@param init_Pi Matrix to initialize the dynamic coefficients.", "") %>
#' <%=ifelse(exists("init_psi"), "@param init_psi Matrix to initialize the steady-state parameters.", "") %>
#' <%=ifelse(exists("init_Sigma"), "@param init_Sigma Matrix to initialize the error covariance.", "") %>
#' <%=ifelse(exists("init_Z"), "@param init_Z Matrix to initialize the latent state.", "") %>
#' <%=ifelse(exists("inv_prior_Pi_Omega"), "@param inv_prior_Pi_Omega The inverse of the prior covariance matrix for Pi.", "") %>
#' <%=ifelse(exists("ip"), "@param ip The number of variables (\\code{n_vars}).", "") %>
#' <%=ifelse(exists("iq"), "@param iq The companion-form dimension (\\code{n_vars*n_lags}).", "") %>
#' <%=ifelse(exists("iT"), "@param iT The sample size (sometimes called \\code{n_T}).", "") %>
#' <%=ifelse(exists("m"), "@param m The mean vector of size \\code{p}.", "") %>
#' <%=ifelse(exists("method"), "@param method The method to use for estimation of the log marginal data density. One of \\code{1} and \\code{2}.", "") %>
#' <%=ifelse(exists("mfbvar_obj"), "@param mfbvar_obj An object of class \\code{mfbvar} containing the results.", "") %>
#' <%=ifelse(exists("monthly_cols"), "@param monthly_cols Column indexes of monthly variables.", "") %>
#' <%=ifelse(exists("M"), "@param M The mean matrix of size \\code{p * q}.", "") %>
#' <%=ifelse(exists("mF"), "@param mF \\code{(n_vars*n_lags) * (n_vars*n_lags)} matrix containing parameters (companion form)", "") %>
#' <%=ifelse(exists("mQ"), "@param mQ \\code{(n_vars*n_lags) * (n_vars*n_lags)} matrix whose \\code{n_vars*n_vars} top-left block is the Cholesky decomposition of the error covariance matrix", "") %>
#' <%=ifelse(exists("mZ"), "@param mZ \\code{T * n_vars} matrix with the observations (\\code{NA} represents missingness)", "") %>
#' <%=ifelse(exists("n_burnin"), "@param n_burnin The number of burn-in replications.", "") %>
#' <%=ifelse(exists("n_comp"), "@param n_comp The length of the companion form vector of data (\\code{n_vars*n_lags}).", "") %>
#' <%=ifelse(exists("n_cores"), "@param n_cores The number of cores to use (if set to 1, computation is done serially).", "") %>
#' <%=ifelse(exists("n_determ"), "@param n_determ The number of deterministic terms.", "") %>
#' <%=ifelse(exists("n_fcst"), "@param n_fcst The number of periods to forecast.", "") %>
#' <%=ifelse(exists("n_lags"), "@param n_lags The number of lags.", "") %>
#' <%=ifelse(exists("n_reps"), "@param n_reps The number of replications.", "") %>
#' <%=ifelse(exists("n_T"), "@param n_T The number of time points.", "") %>
#' <%=ifelse(exists("n_T_"), "@param n_T_ The number of time points (excluding pre-sample).", "") %>
#' <%=ifelse(exists("n_vars"), "@param n_vars The number of variables.", "") %>
#' <%=ifelse(exists("Omega_Pi"), "@param Omega_Pi The \\code{inv_prior_Pi_Omega} multiplied by \\code{prior_Pi} matrix.", "") %>
#' <%=ifelse(exists("P"), "@param P \\code{p * p} covariance matrix.", "") %>
#' <%=ifelse(exists("postsim"), "@param postsim The log marginal data density for \\code{Z}.", "") %>
#' <%=ifelse(exists("Q"), "@param Q \\code{q * q} covariance matrix.", "") %>
#' <%=ifelse(exists("Q_comp"), "@param Q_comp The lower-triangular Cholesky decomposition of the covariance matrix (in companion form).", "") %>
#' <%=ifelse(exists("p_trunc"), "@param p_trunc \\code{1-p_trunc} is the degree of truncation (i.e. \\code{p_trunc=1} is no truncation).", "") %>
#' <%=ifelse(exists("P0"), "@param P0 The covariance matrix of the initial state (\\code{(n_vars*n_lags)*(n_vars*n_lags)}).", "") %>
#' <%=ifelse(exists("Pi"), "@param Pi Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the dynamic coefficients.", "") %>
#' <%=ifelse(exists("Pi_array"), "@param Pi_array Array of draws of Pi from the Gibbs sampler.", "") %>
#' <%=ifelse(exists("Pi_r"), "@param Pi_r The current draw of \\code{Pi} (i.e. \\code{Pi[,, r]}).", "") %>
#' <%=ifelse(exists("Pi_comp"), "@param Pi_comp Matrix with the dynamic coefficients in companion form.", "") %>
#' <%=ifelse(exists("post_nu"), "@param post_nu The posterior of the parameter \\eqn{\\nu}.", "") %>
#' <%=ifelse(exists("post_Pi_center"), "@param post_Pi_center The value at which to do the evaluation (e.g. the posterior mean/median).", "") %>
#' <%=ifelse(exists("post_psi_Omega"), "@param post_psi_Omega The covariance matrix in the posterior, \\eqn{\\bar{\\Omega}_{\\Psi}}.", "") %>
#' <%=ifelse(exists("post_psi_center"), "@param post_psi_center The value at which to do the evaluation (e.g. the posterior mean/median).", "") %>
#' <%=ifelse(exists("post_Sigma_center"), "@param post_Sigma_center The value at which to do the evaluation (e.g. the posterior mean/median).", "") %>
#' <%=ifelse(exists("prior_nu"), "@param prior_nu The prior degrees of freedom.", "") %>
#' <%=ifelse(exists("prior_Pi"), "@param prior_Pi Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the prior for the mean of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_Pi_AR1"), "@param prior_Pi_AR1 The prior means for the AR(1) coefficients.", "") %>
#' <%=ifelse(exists("prior_Pi_mean"), "@param prior_Pi_mean Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the prior for the mean of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_Pi_Omega"), "@param prior_Pi_Omega Matrix of size \\code{(n_vars*n_lags)* (n_vars*n_lags)} containing the prior for (part of) the prior covariance of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_psi_mean"), "@param prior_psi_mean Vector of length \\code{n_determ*n_vars} with the prior means of the steady-state parameters.", "") %>
#' <%=ifelse(exists("prior_psi_Omega"), "@param prior_psi_Omega Matrix of size \\code{(n_determ*n_vars) * (n_determ*n_vars)} with the prior covariance of the steady-state parameters.", "") %>
#' <%=ifelse(exists("prior_psi_int"), "@param prior_psi_int Matrix of size \\code{(n_determ*n_vars) * 2} with the prior 95 \\% prior probability intervals.", "") %>
#' <%=ifelse(exists("prior_S"), "@param prior_S The prior for \\eqn{\\Sigma}.", "") %>
#' <%=ifelse(exists("psi_r"), "@param psi_r The current draw of \\code{psi} (i.e. \\code{psi[r-1,]}).", "") %>
#' <%=ifelse(exists("psi_r1"), "@param psi_r1 The previous draw of \\code{psi} (i.e. \\code{psi[r-1,]}).", "") %>
#' <%=ifelse(exists("S"), "@param S \\code{q * q} scale matrix.", "") %>
#' <%=ifelse(exists("Sigma"), "@param Sigma The covariance matrix.", "") %>
#' <%=ifelse(exists("Sigma_array"), "@param Sigma_array Array of draws of Sigma from the Gibbs sampler.", "") %>
#' <%=ifelse(exists("Sigma_r"), "@param Sigma_r The current draw of \\code{Sigma} (i.e. \\code{Sigma[,, r]}).", "") %>
#' <%=ifelse(exists("smooth_state"), "@param smooth_state Logical, if \\code{TRUE} then the smoothed estimates of the latent states are also returned.", "") %>
#' <%=ifelse(exists("U"), "@param U \\eqn{U} matrix, of size \\code{(n_vars*n_determ*(n_lags+1)) * (n_vars*n_determ)}. This can be obtained using \\code{\\link{build_U}}.", "") %>
#' <%=ifelse(exists("v"), "@param v The degrees of freedom.", "") %>
#' <%=ifelse(exists("verbose"), "@param verbose Logical, if progress should be printed to the console.", "") %>
#' <%=ifelse(exists("V_inv"), "@param V_inv The inverse of the covariance matrix of size \\code{d * d}.", "") %>
#' <%=ifelse(exists("x"), "@param x A vector of size \\code{p}.", "") %>
#' <%=ifelse(exists("X"), "@param X Matrix of size \\code{p * q}.", "") %>
#' <%=ifelse(exists("Y"), "@param Y The data matrix of size \\code{(n_T + n_lags) * n_vars} with \\code{NA} representing missingness. Must correspond well to the specification of \\code{M_Lambda}.", "") %>
#' <%=ifelse(exists("Y_tilde"), "@param Y_tilde The lag-corrected data matrix (with no missing values) of size \\code{n_T * n_vars}.", "") %>
#' <%=ifelse(exists("z"), "@param z A matrix of size \\code{(n_T + n_lags) * n_vars} of data.", "") %>
#' <%=ifelse(exists("Z"), "@param Z The array of draws from the posterior of \\code{Z}.", "") %>
#' <%=ifelse(exists("Z_array"), "@param Z_array The array of draws of Z from the Gibbs sampler.", "") %>
#' <%=ifelse(exists("z0"), "@param z0 A matrix of size \\code{(n_lags*n_vars) * n_vars} of initial values of the latent variable.", "") %>
#' <%=ifelse(exists("Z_1"), "@param Z_1 The matrix \\code{Z[1:n_lags,, 1]} (used as initial value).", "") %>
#' <%=ifelse(exists("Z_r1"), "@param Z_r1 The previous draw of \\code{Z} (i.e. \\code{Z[,, r-1]}).", "") %>


