#' @title Template titel
#' <%=ifelse(exists("aggregation"), "@param aggregation A character vector of length \\code{n_vars} with elements being \\code{'identity'}, \\code{'average'} or \\code{'triangular'} to indicate the type of aggregation scheme to assume.", "") %>
#' <%=ifelse(exists("chisq_val"), "@param chisq_val The value in the corresponding chi-square distribution; if the normal quadratic form exceeds this, the pdf is 0.", "") %>
#' <%=ifelse(exists("check_roots"), "@param check_roots Logical, if roots of the companion matrix are to be checked to ensure stationarity.", "") %>
#' <%=ifelse(exists("d"), "@param d The matrix of size \\code{(n_T + n_lags) * n_determ} of deterministic terms.", "") %>
#' <%=ifelse(exists("D"), "@param D The \\code{D} matrix (from \\code{\\link{build_DD}}).", "") %>
#' <%=ifelse(exists("d_fcst"), "@param d_fcst The deterministic terms for the forecasting period.", "") %>
#' <%=ifelse(exists("Lambda"), "@param Lambda The Lambda matrix (size \\code{n_vars* (n_vars*n_lags)}).", "") %>
#' <%=ifelse(exists("lambda1"), "@param lambda1 The overall tightness.", "") %>
#' <%=ifelse(exists("lambda2"), "@param lambda2 The lag decay.", "") %>
#' <%=ifelse(exists("lH"), "@param lH A list of length \\code{n_T}, where \\code{M_Lambda[[t]]} corresponds to \\eqn{M_t\\Lambda}. The column dimension of each element should be \\code{n_lags*n_vars}, but the row dimension may vary.", "") %>
#' <%=ifelse(exists("init_Pi"), "@param init_Pi Matrix to initialize the dynamic coefficients.", "") %>
#' <%=ifelse(exists("init_psi"), "@param init_psi Matrix to initialize the steady-state parameters.", "") %>
#' <%=ifelse(exists("init_Sigma"), "@param init_Sigma Matrix to initialize the error covariance.", "") %>
#' <%=ifelse(exists("init_Z"), "@param init_Z Matrix to initialize the latent state.", "") %>
#' <%=ifelse(exists("inv_prior_pi_omega"), "@param inv_prior_pi_omega The inverse of the prior covariance matrix for Pi.", "") %>
#' <%=ifelse(exists("m"), "@param m The mean vector of size \\code{p}.", "") %>
#' <%=ifelse(exists("M"), "@param M The mean matrix of size \\code{p * q}.", "") %>
#' <%=ifelse(exists("n_burnin"), "@param n_burnin The number of burn-in replications.", "") %>
#' <%=ifelse(exists("n_determ"), "@param n_determ The number of deterministic terms.", "") %>
#' <%=ifelse(exists("n_fcst"), "@param n_fcst The number of periods to forecast.", "") %>
#' <%=ifelse(exists("n_lags"), "@param n_lags The number of lags.", "") %>
#' <%=ifelse(exists("n_reps"), "@param n_reps The number of replications.", "") %>
#' <%=ifelse(exists("n_T"), "@param n_T The number of time points.", "") %>
#' <%=ifelse(exists("n_vars"), "@param n_vars The number of variables.", "") %>
#' <%=ifelse(exists("nu"), "@param nu The parameter \\eqn{\\nu}.", "") %>
#' <%=ifelse(exists("omega_pi"), "@param omega_pi The \\code{inv_prior_pi_omega} multiplied by \\code{prior_pi} matrix.", "") %>
#' <%=ifelse(exists("P"), "@param P \\code{p * p} covariance matrix.", "") %>
#' <%=ifelse(exists("p_trunc"), "@param p_trunc \\code{1-p_trunc} is the degree of truncation (i.e. \\code{p_trunc=1} is no truncation).", "") %>
#' <%=ifelse(exists("Pi"), "@param Pi Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the dynamic coefficients.", "") %>
#' <%=ifelse(exists("Pi_r"), "@param Pi_r The current draw of \\code{Pi} (i.e. \\code{Pi[,, r]}).", "") %>
#' <%=ifelse(exists("prior_pi"), "@param prior_pi Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the prior for the mean of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_mean"), "@param prior_mean The prior means for the AR(1) coefficients.", "") %>
#' <%=ifelse(exists("prior_mean_pi"), "@param prior_mean_pi Matrix of size \\code{n_vars * (n_vars*n_lags)} containing the prior for the mean of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_mean_psi"), "@param prior_mean_psi Vector of length \\code{n_determ*n_vars} with the prior means of the steady-state parameters.", "") %>
#' <%=ifelse(exists("prior_nu"), "@param prior_nu The prior degrees of freedom.", "") %>
#' <%=ifelse(exists("prior_pi_omega"), "@param prior_pi_omega Matrix of size \\code{(n_vars*n_lags)* (n_vars*n_lags)} containing the prior for (part of) the prior covariance of the dynamic coefficients.", "") %>
#' <%=ifelse(exists("prior_psi"), "@param prior_psi Vector of length \\code{n_determ*n_vars} with the prior means of the steady-state parameters.", "") %>
#' <%=ifelse(exists("prior_psi_omega"), "@param prior_psi_omega Matrix of size \\code{(n_determ*n_vars) * (n_determ*n_vars)} with the prior covariance of the steady-state parameters.", "") %>
#' <%=ifelse(exists("prior_s"), "@param prior_s The prior for \\eqn{\\Sigma}.", "") %>
#' <%=ifelse(exists("prior_var_psi"), "@param prior_var_psi Matrix of size \\code{(n_determ*n_vars) * (n_determ*n_vars)} with the prior covariance of the steady-state parameters.", "") %>
#' <%=ifelse(exists("psi_r"), "@param psi_r The current draw of \\code{psi} (i.e. \\code{psi[r-1,]}).", "") %>
#' <%=ifelse(exists("psi_r1"), "@param psi_r1 The previous draw of \\code{psi} (i.e. \\code{psi[r-1,]}).", "") %>
#' <%=ifelse(exists("S"), "@param S \\code{q * q} scale matrix.", "") %>
#' <%=ifelse(exists("sigma"), "@param sigma The covariance matrix.", "") %>
#' <%=ifelse(exists("Sigma"), "@param Sigma The covariance matrix.", "") %>
#' <%=ifelse(exists("Sigma_r"), "@param Sigma_r The current draw of \\code{Sigma} (i.e. \\code{Sigma[,, r]}).", "") %>
#' <%=ifelse(exists("smooth_state"), "@param smooth_state Logical, if \\code{TRUE} then the smoothed estimates of the latent states are also returned.", "") %>
#' <%=ifelse(exists("U"), "@param U \\eqn{U} matrix, of size \\code{(n_vars*n_determ*(n_lags+1)) * (n_vars*n_determ)}. This can be obtained using \\code{\\link{build_U}}.", "") %>
#' <%=ifelse(exists("v"), "@param v The degrees of freedom.", "") %>
#' <%=ifelse(exists("V_inv"), "@param V_inv The inverse of the covariance matrix of size \\code{d * d}.", "") %>
#' <%=ifelse(exists("x"), "@param x A vector of size \\code{p}.", "") %>
#' <%=ifelse(exists("X"), "@param X Matrix of size \\code{p * q}.", "") %>
#' <%=ifelse(exists("Y"), "@param Y The data matrix of size \\code{(n_T + n_lags) * n_vars} with \\code{NA} representing missingness. Must correspond well to the specification of \\code{M_Lambda}.", "") %>
#' <%=ifelse(exists("Y_tilde"), "@param Y_tilde The lag-corrected data matrix (with no missing values) of size \\code{n_T * n_vars}.", "") %>
#' <%=ifelse(exists("z"), "@param z A matrix of size \\code{(n_T + n_lags) * n_vars} of data.", "") %>
#' <%=ifelse(exists("Z_1"), "@param Z_1 The matrix \\code{Z[1:n_lags,, 1]} (used as initial value).", "") %>
#' <%=ifelse(exists("Z_r1"), "@param Z_r1 The previous draw of \\code{Z} (i.e. \\code{Z[,, r-1]}).", "") %>


